const $=s=>document.querySelector(s);
const KEY="ug_listings_v30";
const DEFAULTS=[
{id:1,title:"Önerler'de Yatırımlık Arsa",type:"Arsa",deal:"Satılık",status:"Aktif",location:"Çorlu / Önerler",price:"11.500.000 TL",m2:"1001",ada:"334",parsel:"15",zoning:"Konut",description:"Yatırım ve proje için değerlendirilebilecek örnek portföy.",photos:[]},
{id:2,title:"Projeden Satılık 3+1 Daire",type:"Daire",deal:"Satılık",status:"Aktif",location:"Çorlu",price:"4.250.000 TL",m2:"125",netM2:"110",rooms:"3+1",floor:"3",floors:"5",heating:"Doğalgaz Kombi",elevator:true,parking:true,description:"Modern ve kullanışlı örnek daire portföyü.",photos:[]}
];
let listings=JSON.parse(localStorage.getItem(KEY)||"null")||DEFAULTS,editingPhotos=[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(listings));
const isLand=t=>["Arsa"].includes(t);
const emoji=t=>t==="Arsa"?"🌄":t==="Daire"?"🏢":t==="Villa"?"🏡":t==="Müstakil Ev"?"🏠":t==="Dükkan"?"🏪":t==="Ofis"?"🏢":t==="Depo"?"🏭":"🏬";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function card(l){let p=(l.photos||[])[0];return `<article class="card" data-id="${l.id}"><div class="cardImg">${p?`<img src="${p}" alt="">`:emoji(l.type)}</div><div class="cardBody"><span class="tag">${esc(l.deal||"Satılık")} • ${esc(l.type)}</span><span class="status">${esc(l.status||"Aktif")}</span><h3>${esc(l.title)}</h3><div class="location">📍 ${esc(l.location)}</div><div class="price">${esc(l.price)}</div><div class="specs">${l.m2?`<span class="spec">${esc(l.m2)} m²</span>`:""}${isLand(l.type)&&l.ada?`<span class="spec">Ada ${esc(l.ada)}</span>`:""}${isLand(l.type)&&l.parsel?`<span class="spec">Parsel ${esc(l.parsel)}</span>`:""}${!isLand(l.type)&&l.rooms?`<span class="spec">${esc(l.rooms)}</span>`:""}</div></div></article>`}
function render(){let q=$("#searchInput").value.toLowerCase().trim(),t=$("#typeFilter").value,d=$("#dealFilter").value;let rows=listings.filter(l=>(!t||l.type===t)&&(!d||l.deal===d)&&[l.title,l.location,l.ada,l.parsel,l.description,l.type,l.deal].join(" ").toLowerCase().includes(q));$("#listingGrid").innerHTML=rows.map(card).join("");$("#listingCount").textContent=listings.filter(x=>(x.status||"Aktif")==="Aktif").length;$("#resultText").textContent=rows.length+" ilan";$("#emptyState").classList.toggle("hidden",rows.length>0);document.querySelectorAll(".card").forEach(c=>c.onclick=()=>showDetail(+c.dataset.id));renderAdmin()}
function feature(label,val){return val?`<div class="feature"><small>${label}</small><br><b>${esc(val===true?"Var":val)}</b></div>`:""}
function showDetail(id){let l=listings.find(x=>x.id===id);if(!l)return;let photos=l.photos||[],features=isLand(l.type)?[feature("Toplam Alan",l.m2&&l.m2+" m²"),feature("Ada",l.ada),feature("Parsel",l.parsel),feature("İmar",l.zoning),feature("Emsal",l.emsal),feature("Tapu",l.deed),feature("Yola Cephe",l.frontage)]:[feature("Brüt Alan",l.m2&&l.m2+" m²"),feature("Net Alan",l.netM2&&l.netM2+" m²"),feature("Oda",l.rooms),feature("Kat",l.floor),feature("Bina Katı",l.floors),feature("Bina Yaşı",l.age),feature("Banyo",l.bathrooms),feature("Isıtma",l.heating),feature("Balkon",l.balcony),feature("Asansör",l.elevator),feature("Otopark",l.parking),feature("Ebeveyn Banyosu",l.ensuite),feature("İskan",l.iskan),feature("Krediye Uygun",l.credit),feature("Eşyalı",l.furnished),feature("Bahçe",l.garden)];$("#detailContent").innerHTML=`<div class="detailHero">${photos[0]?`<img src="${photos[0]}">`:emoji(l.type)}</div><p><span class="tag">${esc(l.deal)} • ${esc(l.type)}</span> <span class="status">${esc(l.status)}</span></p><h2>${esc(l.title)}</h2><p class="location">📍 ${esc(l.location)}</p><div class="detailPrice">${esc(l.price)}</div>${photos.length>1?`<div class="gallery">${photos.map(x=>`<img src="${x}">`).join("")}</div>`:""}<div class="featureGrid">${features.join("")}</div><p>${esc(l.description||"Detaylı bilgi için iletişime geçebilirsiniz.")}</p><div class="detailActions"><a class="primary" href="tel:+905061347675">📞 Ara</a><a class="primary" target="_blank" href="https://wa.me/905061347675?text=${encodeURIComponent(l.title+" ilanı hakkında bilgi almak istiyorum.")}">💬 WhatsApp</a><button class="secondary" onclick="shareListing(${l.id})">↗ Paylaş</button></div>`;$("#detailDialog").showModal()}
window.shareListing=async id=>{let l=listings.find(x=>x.id===id),data={title:l.title,text:`${l.title} - ${l.price} - ${l.location}`,url:location.href};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.text+" "+data.url);alert("İlan bilgisi kopyalandı.")}}
function renderAdmin(){let el=$("#adminList");el.innerHTML=listings.map(l=>`<div class="adminItem"><div><b>${esc(l.title)}</b><div class="muted">${esc(l.deal)} • ${esc(l.status)} • ${esc(l.price)}</div></div><div class="adminBtns"><button class="edit" data-edit="${l.id}">✏️</button><button class="danger" data-del="${l.id}">🗑️</button></div></div>`).join("");el.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Bu ilan silinsin mi?")){listings=listings.filter(x=>x.id!==+b.dataset.del);save();render()}});el.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editListing(+b.dataset.edit))}
function setTypeFields(){let land=isLand($("#adminType").value);$("#landFields").classList.toggle("hidden",!land);$("#buildingFields").classList.toggle("hidden",land)}
$("#adminType").onchange=setTypeFields;
function previewPhotos(){let p=$("#photoPreview");p.innerHTML=editingPhotos.map((x,i)=>`<div class="photoThumb"><img src="${x}"><button type="button" data-rm="${i}">×</button></div>`).join("");p.querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{editingPhotos.splice(+b.dataset.rm,1);previewPhotos()})}
function resizeFile(file){return new Promise((res,rej)=>{let r=new FileReader;r.onload=()=>{let img=new Image;img.onload=()=>{let max=1280,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext("2d").drawImage(img,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.78))};img.onerror=rej;img.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
$("#photoInput").onchange=async e=>{let files=[...e.target.files].slice(0,10-editingPhotos.length);for(let f of files){try{editingPhotos.push(await resizeFile(f))}catch{}}previewPhotos();e.target.value=""}
function editListing(id){let l=listings.find(x=>x.id===id),f=$("#adminForm");if(!l)return;Object.keys(l).forEach(k=>{let e=f.elements[k];if(!e||k==="photos")return;if(e.type==="checkbox")e.checked=!!l[k];else e.value=l[k]??""});f.elements.editId.value=id;editingPhotos=[...(l.photos||[])];previewPhotos();setTypeFields();$("#saveListing").textContent="✓ Değişiklikleri Kaydet";$("#cancelEdit").classList.remove("hidden");f.scrollIntoView({behavior:"smooth"})}
function resetForm(){let f=$("#adminForm");f.reset();f.elements.editId.value="";editingPhotos=[];previewPhotos();setTypeFields();$("#saveListing").textContent="＋ İlanı Kaydet";$("#cancelEdit").classList.add("hidden")}
$("#adminForm").onsubmit=e=>{e.preventDefault();let f=e.target,d=Object.fromEntries(new FormData(f)),id=+d.editId;delete d.editId;["balcony","elevator","parking","ensuite","iskan","credit","furnished","garden"].forEach(k=>d[k]=f.elements[k].checked);d.photos=[...editingPhotos];if(isLand(d.type)){["rooms","floor","floors","age","bathrooms","heating","balcony","elevator","parking","ensuite","iskan","credit","furnished","garden","netM2"].forEach(k=>delete d[k])}else{["ada","parsel","zoning","emsal","deed","frontage"].forEach(k=>delete d[k])}if(id){let i=listings.findIndex(x=>x.id===id);listings[i]={...listings[i],...d,id}}else listings.unshift({id:Date.now(),...d});try{save()}catch(e){alert("Telefon depolama sınırına ulaştı. Daha az veya daha küçük fotoğraf kullanın.");return}resetForm();render();alert(id?"İlan güncellendi.":"İlan eklendi.")};
$("#cancelEdit").onclick=resetForm;
$("#searchInput").oninput=render;$("#typeFilter").onchange=render;$("#dealFilter").onchange=render;$("#navListings").onclick=()=>$("#listingGrid").scrollIntoView({behavior:"smooth"});$("#homeBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"});$("#openSellForm").onclick=()=>$("#sellDialog").showModal();
const login=$("#adminLogin"),pass=$("#adminPassword"),err=$("#adminError");$("#openAdmin").onclick=()=>{pass.value="";err.textContent="";login.classList.add("show");setTimeout(()=>pass.focus(),100)};$("#adminLoginBtn").onclick=()=>{if(pass.value==="081008"){login.classList.remove("show");$("#adminDialog").showModal()}else{err.textContent="Şifre hatalı!";pass.value=""}};$("#adminCancelBtn").onclick=()=>login.classList.remove("show");pass.onkeydown=e=>{if(e.key==="Enter")$("#adminLoginBtn").click()};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());
$("#sellForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),msg=`Merhaba, gayrimenkulümü değerlendirmek istiyorum.\n\nAd Soyad: ${d.name}\nTelefon: ${d.phone}\nTür: ${d.type}\nKonum: ${d.location}\nBilgi: ${d.note||"-"}`;window.open("https://wa.me/905061347675?text="+encodeURIComponent(msg),"_blank")};
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").classList.add("hidden")}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){alert("iPhone'da Safari'de Paylaş simgesine dokunun ve 'Ana Ekrana Ekle' seçeneğini kullanın.")}else alert("Tarayıcı menüsünden 'Uygulamayı yükle' veya 'Ana ekrana ekle' seçeneğini kullanın.")};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=30"));
setTypeFields();render();