const DEFAULTS=[{id:1,title:"Önerler'de Yatırımlık Arsa",type:"Arsa",status:"Aktif",location:"Çorlu / Önerler",price:"11.500.000 TL",m2:"1.001",ada:"334",parsel:"15",description:"Yatırım ve proje için değerlendirilebilecek portföy.",image:""},{id:2,title:"Projeden Satılık 1+1 Daire",type:"Daire",status:"Aktif",location:"Çorlu",price:"2.750.000 TL",m2:"45",ada:"",parsel:"",description:"Asansörlü, açık otoparklı, iskanlı daire.",image:""},{id:3,title:"Kat Karşılığı Arsa Fırsatı",type:"Kat Karşılığı",status:"Aktif",location:"Çorlu / Önerler",price:"Görüşülür",m2:"537",ada:"320",parsel:"3",description:"Müteahhit ve yatırımcılara uygun portföy.",image:""}];
const KEY="ug_listings_v2",$=s=>document.querySelector(s);let listings=JSON.parse(localStorage.getItem(KEY)||"null")||DEFAULTS;const save=()=>localStorage.setItem(KEY,JSON.stringify(listings));
function emoji(t){return t==="Arsa"?"🌄":t==="Daire"?"🏢":t==="Villa"?"🏡":t==="İşyeri"?"🏬":t==="Kiralık"?"🔑":"🏗️"}
function card(l){return `<article class="card" data-id="${l.id}"><div class="cardImg">${l.image?`<img src="${l.image}" alt="${l.title}">`:emoji(l.type)}</div><div class="cardBody"><span class="tag">${l.type}</span><span class="status">${l.status||"Aktif"}</span><h3>${l.title}</h3><div class="location">📍 ${l.location}</div><div class="price">${l.price}</div><div class="specs">${l.m2?`<span class="spec">${l.m2} m²</span>`:""}${l.ada?`<span class="spec">Ada ${l.ada}</span>`:""}${l.parsel?`<span class="spec">Parsel ${l.parsel}</span>`:""}</div></div></article>`}
function render(){const q=$("#searchInput").value.toLowerCase().trim(),t=$("#typeFilter").value;const rows=listings.filter(l=>(!t||l.type===t)&&[l.title,l.location,l.ada,l.parsel,l.description,l.type].join(" ").toLowerCase().includes(q));$("#listingGrid").innerHTML=rows.map(card).join("");$("#listingCount").textContent=listings.filter(x=>(x.status||"Aktif")==="Aktif").length;$("#resultText").textContent=rows.length+" ilan";$("#emptyState").classList.toggle("hidden",rows.length>0);document.querySelectorAll(".card").forEach(c=>c.onclick=()=>showDetail(+c.dataset.id));renderAdmin()}
function showDetail(id){const l=listings.find(x=>x.id===id);if(!l)return;$("#detailContent").innerHTML=`<div class="detailHero">${l.image?`<img src="${l.image}" alt="">`:emoji(l.type)}</div><p><span class="tag">${l.type}</span> <span class="status">${l.status||"Aktif"}</span></p><h2>${l.title}</h2><p class="location">📍 ${l.location}</p><div class="detailPrice">${l.price}</div><div class="detailGrid">${l.m2?`<div><small>Alan</small><b>${l.m2} m²</b></div>`:""}${l.ada?`<div><small>Ada</small><b>${l.ada}</b></div>`:""}${l.parsel?`<div><small>Parsel</small><b>${l.parsel}</b></div>`:""}</div><p>${l.description||"Detaylı bilgi için iletişime geçebilirsiniz."}</p><div class="detailActions"><a href="tel:+905061347675">📞 Ara</a><a target="_blank" href="https://wa.me/905061347675?text=${encodeURIComponent(l.title+" ilanı hakkında bilgi almak istiyorum.")}">💬 WhatsApp</a></div>`;$("#detailDialog").showModal()}
function renderAdmin(){const el=$("#adminList");el.innerHTML=listings.map(l=>`<div class="adminItem"><div><b>${l.title}</b><div class="muted">${l.status||"Aktif"} • ${l.price}</div></div><div class="adminBtns"><button class="edit" data-edit="${l.id}">✏️</button><button class="danger" data-del="${l.id}">🗑️</button></div></div>`).join("");el.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Bu ilan silinsin mi?")){listings=listings.filter(x=>x.id!==+b.dataset.del);save();render()}});el.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editListing(+b.dataset.edit))}
function editListing(id){const l=listings.find(x=>x.id===id),f=$("#adminForm");if(!l)return;["title","type","status","location","price","m2","ada","parsel","image","description"].forEach(k=>{if(f.elements[k])f.elements[k].value=l[k]||""});f.elements.editId.value=id;$("#saveListing").textContent="✓ Değişiklikleri Kaydet";$("#cancelEdit").classList.remove("hidden");f.scrollIntoView({behavior:"smooth"})}
function resetForm(){const f=$("#adminForm");f.reset();f.elements.editId.value="";$("#saveListing").textContent="＋ İlanı Kaydet";$("#cancelEdit").classList.add("hidden")}
$("#searchInput").oninput=render;$("#typeFilter").onchange=render;$("#navListings").onclick=()=>$("#listingGrid").scrollIntoView({behavior:"smooth"});$("#homeBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"});$("#openSellForm").onclick=()=>$("#sellDialog").showModal();
const login=$("#adminLogin"),pass=$("#adminPassword"),err=$("#adminError");$("#openAdmin").onclick=()=>{pass.value="";err.textContent="";login.classList.add("show");setTimeout(()=>pass.focus(),100)};$("#adminLoginBtn").onclick=()=>{if(pass.value==="081008"){login.classList.remove("show");$("#adminDialog").showModal()}else{err.textContent="Şifre hatalı!";pass.value=""}};$("#adminCancelBtn").onclick=()=>login.classList.remove("show");pass.onkeydown=e=>{if(e.key==="Enter")$("#adminLoginBtn").click()};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());$("#cancelEdit").onclick=resetForm;
$("#sellForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const msg=`Merhaba, gayrimenkulümü değerlendirmek istiyorum.\n\nAd Soyad: ${d.name}\nTelefon: ${d.phone}\nTür: ${d.type}\nKonum: ${d.location}\nBilgi: ${d.note||"-"}`;window.open("https://wa.me/905061347675?text="+encodeURIComponent(msg),"_blank")};
$("#adminForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),id=Number(d.editId);delete d.editId;if(id){const i=listings.findIndex(x=>x.id===id);if(i>=0)listings[i]={...listings[i],...d}}else listings.unshift({id:Date.now(),...d});save();resetForm();render();alert(id?"İlan güncellendi.":"İlan eklendi.")};
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").classList.add("hidden")};render();
